version: 1.0.{build}
image: Visual Studio 2015

clone_depth: 1

platform:
    - ARM
    - x64
    - Win32

configuration:
    - Unicode Debug
    - Unicode Release

environment:
    DepsDir: c:\projects\deps
    BoostMajor: 1
    BoostMinor: 58
    BoostPatch: 0
    BoostVerUnderscore: $(BoostMajor)_$(BoostMinor)_$(BoostPatch)
    BoostVerDot: $(BoostMajor).$(BoostMinor).$(BoostPatch)
    BoostBase: boost_$(BoostVerUnderscore)
    BoostArchive: $(BoostBase).7z
    BoostUrl: https://sourceforge.net/projects/boost/files/boost/$(BoostVerDot)/$(BoostArchive)/download
    BoostDir: $(DepsDir)\$(BoostBase)
    B2: b2 --with-regex toolset=msvc-14.0 --build-type=complete link=static runtime-link=static threading=multi
    NoCache: 1

cache:
    - $(BoostDir)\bin.v2 -> appveyor.yml
    - $(BoostDir)\boost -> appveyor.yml

install:
    - if exist %BoostDir%\bin.v2 if exist %BoostDir%\boost set NoCache=0
    - if %NoCache% equ 1 if exist %BoostDir% rmdir /S /Q %BoostDir%
    - if %NoCache% equ 1 appveyor DownloadFile "%BoostUrl%" -FileName "%TEMP%\%BoostArchive%"
    - if %NoCache% equ 1 7z x -o%DepsDir% "%TEMP%\%BoostArchive%"
    - if %NoCache% equ 1 del "%TEMP%\%BoostArchive%"
    - if %NoCache% equ 1 cd %BoostDir%
    - if %NoCache% equ 1 bootstrap
    - if %NoCache% equ 1 if "%platform%" == "ARM" %B2% architecture=arm cxxflags=/D_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1
    - if %NoCache% equ 1 if "%platform%" == "x64" %B2% architecture=x86 address-model=64
    - if %NoCache% equ 1 if "%platform%" == "Win32" %B2% architecture=x86 address-model=32
    - if %NoCache% equ 1 (cd bin.v2 && del /S *.obj *.rsp)
    - echo BOOSTPATH=%BoostDir% > c:\projects\notepad-plus-plus\scintilla\boostregex\boostpath.mak
    - echo BOOSTLIBPATH=%BoostDir%\bin.v2\libs\regex\build\msvc-14.0 >> c:\projects\notepad-plus-plus\scintilla\boostregex\boostpath.mak
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="ARM" set archi=x86_arm
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%

build:
    verbosity: minimal

build_script:
    - cd c:\projects\notepad-plus-plus\scintilla\win32
    - set NMAKE_ARGS=dummy
    - if "%configuration%"=="Unicode Debug" set NMAKE_ARGS=%NMAKE_ARGS% DEBUG=1
    - if "%platform%"=="ARM" set NMAKE_ARGS=%NMAKE_ARGS% SCINTILLA_ARM_BUILD=1
    - if "%platform%"=="ARM" set NMAKE_ARGS=%NMAKE_ARGS% BUILDTARGETPATH=architecture-arm\
    - if "%platform%"=="X64" set NMAKE_ARGS=%NMAKE_ARGS% BUILDTARGETPATH=address-model-64\
    - nmake %NMAKE_ARGS:~5% -f scintilla.mak
    - cd c:\projects\notepad-plus-plus\PowerEditor\visual.net\
    - msbuild notepadPlus.vcxproj /p:configuration="%configuration%" /p:platform="%platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd c:\projects\notepad-plus-plus\
    - ps: |
        $nppFileName = "Notepad++.$env:PLATFORM.$env:CONFIGURATION.exe"
        $pdbFileName = "npp.$env:PLATFORM.$env:CONFIGURATION.pdb"

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Unicode Release") {
            Push-AppveyorArtifact "PowerEditor\bin64\Notepad++.exe" -FileName "$nppFileName"
        }

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Unicode Debug") {
            Push-AppveyorArtifact "PowerEditor\visual.net\x64\Unicode Debug\Notepad++.exe" -FileName "$nppFileName"
        }

        if ($env:PLATFORM -eq "Win32" -and $env:CONFIGURATION -eq "Unicode Release") {
            Push-AppveyorArtifact "PowerEditor\bin\Notepad++.exe" -FileName "$nppFileName"
        }

        if ($env:PLATFORM -eq "Win32" -and $env:CONFIGURATION -eq "Unicode Debug") {
            Push-AppveyorArtifact "PowerEditor\visual.net\Unicode Debug\Notepad++.exe" -FileName "$nppFileName"
        }

        if ($env:PLATFORM -eq "ARM" -and $env:CONFIGURATION -eq "Unicode Release") {
            Push-AppveyorArtifact "PowerEditor\bin-arm\Notepad++.exe" -FileName "$nppFileName"
        }

        if ($env:PLATFORM -eq "ARM" -and $env:CONFIGURATION -eq "Unicode Debug") {
            Push-AppveyorArtifact "PowerEditor\visual.net\arm\Unicode Debug\Notepad++.exe" -FileName "$nppFileName"
        }

        Push-AppveyorArtifact "scintilla\bin\SciLexer.dll" -FileName "SciLexer.$env:PLATFORM.$env:CONFIGURATION.dll"
